### ISSUE TITLE
Prepare first release

### ISSUE THREAD

**Issue by sboeckelmann** [reactiverse/opensearch-client#4]
- resolve https://github.com/reactiverse/opensearch-client/issues/1
- review documentation
- adjust CI/CD: must be referencing main branch for release builds
- require GPG key for deployment signing

**Comment by sboeckelmann** [comment]
@tsegismont 
Can you please support me for getting proper code signing / deployment gpg keys?

**Comment by tsegismont** [comment]
@sboeckelmann have you seen replies in https://github.com/reactiverse/reactiverse/issues/17 ? Still blocked?

**Comment by sboeckelmann** [comment]
> @sboeckelmann have you seen replies in https://github.com/reactiverse/reactiverse/issues/17 ? Still blocked?

I think I will be fine, just didn't find any time to do it yet. 
Will setup my GPG keys and let you know.

**Comment by sboeckelmann** [comment]
still unable to setup with ci build. I am lacking project privileges to setup secrets.
had to deploy release from local

**Comment by tsegismont** [comment]
@sboeckelmann I've granted you with Admin role on this repository, you should be able to do it now. Otherwise, please tell me.
